# Generated by Django 6.0.2 on 2026-02-21 07:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('director', 'Director'), ('project_director', 'Project Director'), ('project_manager', 'Project Manager'), ('assistant_project_manager', 'Assistant Project Manager'), ('developer', 'Developer'), ('pending', 'Pending Approval')], max_length=40)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField(unique=True, verbose_name='S.No.')),
                ('website_url', models.URLField(max_length=300, verbose_name='Website URL')),
                ('stakeholder_ministry', models.CharField(blank=True, max_length=200, verbose_name='Stakeholder - Ministry')),
                ('stakeholder_department', models.CharField(blank=True, max_length=200, verbose_name='Stakeholder - Department')),
                ('stakeholder_state', models.CharField(blank=True, max_length=120, verbose_name='Stakeholder - State')),
                ('stakeholder_state_ministry_department', models.CharField(blank=True, max_length=240, verbose_name='Stakeholder - State Ministry/Department')),
                ('stakeholder_organization', models.CharField(blank=True, max_length=240, verbose_name='Stakeholder - Organization')),
                ('initiative_scheme_project_portal', models.CharField(max_length=300, verbose_name='Initiative/Scheme/Project Portal')),
                ('genesis', models.TextField(blank=True, verbose_name='Genesis')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('project_manager_gis', models.CharField(blank=True, max_length=150, verbose_name='Project Manager - GIS')),
                ('project_manager_sw_mobi', models.CharField(blank=True, max_length=150, verbose_name='Project Manager - S/W & Mobi')),
                ('start', models.DateField(verbose_name='Start')),
                ('end', models.DateField(verbose_name='End')),
                ('status', models.CharField(max_length=120, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='RoleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('super_admin', 'Super Admin'), ('director', 'Director'), ('project_director', 'Project Director'), ('project_manager', 'Project Manager'), ('assistant_project_manager', 'Assistant Project Manager'), ('developer', 'Developer'), ('pending', 'Pending Approval')], max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_role_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_role', models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('director', 'Director'), ('project_director', 'Project Director'), ('project_manager', 'Project Manager'), ('assistant_project_manager', 'Assistant Project Manager'), ('developer', 'Developer'), ('pending', 'Pending Approval')], max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.project')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('assigned_to__isnull', False)), fields=('project', 'assigned_to'), name='unique_project_assignment_per_user'), models.UniqueConstraint(condition=models.Q(('assigned_role__gt', '')), fields=('project', 'assigned_role'), name='unique_project_assignment_per_role')],
            },
        ),
    ]
