from django.urls import path

from .views import (
    assign_project_view,
    assign_to_view,
    dashboard_view,
    excel_entry_view,
    help_view,
    login_view,
    logout_view,
    project_create_view,
    project_detail_view,
    project_delete_view,
    project_edit_view,
    profile_view,
    DirectorPasswordChangeView,
    projects_download_excel_view,
    signup_view,
    view_projects_view,
    contact_us_view,
    chat_view,
    notifications_view,
    notification_read_view,
    notifications_read_all_view,
    role_access_view,
    role_request_view,
    super_admin_dashboard_view,
    super_admin_users_view,
)

urlpatterns = [
    path("", dashboard_view, name="dashboard"),
    path("dashboard/", dashboard_view, name="dashboard_alias"),
    path("super-admin/", super_admin_dashboard_view, name="super_admin_dashboard"),
    path("super-admin/users/", super_admin_users_view, name="super_admin_users"),
    path("signup/", signup_view, name="signup"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("projects/new/", project_create_view, name="project_create"),
    path("projects/<int:project_id>/", project_detail_view, name="project_detail"),
    path("projects/view-projects/", view_projects_view, name="view_projects"),
    path("projects/download-excel/", projects_download_excel_view, name="projects_download_excel"),
    path("projects/assign-project/", assign_project_view, name="assign_project"),
    path("projects/assign-to/", assign_to_view, name="assign_to"),
    path("projects/excel-entry/", excel_entry_view, name="excel_entry"),
    path("profile/", profile_view, name="profile"),
    path("profile/change-password/", DirectorPasswordChangeView.as_view(), name="change_password"),
    path("help/", help_view, name="help_page"),
    path("contact-us/", contact_us_view, name="contact_us"),
    path("chat/", chat_view, name="chat_page"),
    path("notifications/", notifications_view, name="notifications_page"),
    path("notifications/read/<int:notification_id>/", notification_read_view, name="notification_read"),
    path("notifications/read-all/", notifications_read_all_view, name="notifications_read_all"),
    path("roles/request/", role_request_view, name="role_request"),
    path("roles/access/", role_access_view, name="role_access"),
    path("projects/<int:project_id>/delete/", project_delete_view, name="project_delete"),
    path("projects/<int:project_id>/edit/", project_edit_view, name="project_edit"),
]
